export default [
  {
    title: "Meet Our Team",
    desc: "We are led by a group of highly motivated people with diverse backgrounds and extensive experience to unlock creativity around every corner.",
  },
  {
    title: "Temui Tim Kami",
    desc: "Kami dipimpin oleh sekelompok orang yang sangat termotivasi dengan latar belakang yang beragam dan pengalaman yang luas untuk membuka kreativitas di setiap sudut.",
  },
];
